name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Loop through the repository links
      - name: Clone repositories
        run: |
          mkdir repos
          while read -r repo; do
            git clone "$repo" repos/$(basename "$repo" .git)
          done < repositories.txt

      # Build and push Docker images
      - name: Build and push Docker images
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          for dir in repos/*; do
            IMAGE_NAME="ghcr.io/$(basename "$dir",,)"
            docker buildx build --platform linux/amd64 -t "$IMAGE_NAME:latest" --push "$dir"
            SIZE=$(docker image inspect "$IMAGE_NAME:latest" --format='{{.Size}}')
            echo "- [$IMAGE_NAME:latest](https://ghcr.io/${{ github.repository_owner }}/$(basename "$dir")) - ${SIZE}" >> README.md
          done

      # Commit updated README.md
      - name: Commit README changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with image tags and sizes"
          git push
